apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-java-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-java-app
  template:
    metadata:
      labels:
        app: demo-java-app
    spec:
      containers:
      - name: demo-java-app
        image: bssshanky1991/demo-java-app:v1
        imagePullPolicy: Always